image:
  node:latest
  
stages:
  - test
  - build
  - package
  
# These folders are cached between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

test:
  stage: test
  script:
    - npm run prettier:ci
    - npm run ts
    - npm run test:coverage

build:
  stage: build
  script:
    - npm run build
  artifacts:
    name: '$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG'
    paths:
      - build/

package-win:
  stage: package
  image: electronuserland/builder:wine
  only:
    - tags
  script:
    - npm run package:win
  artifacts:
    name: '$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG'
    paths:
      - release/*.msi
      - release/*.exe

package-linux:
  stage: package
  image: electronuserland/builder:latest
  only:
    - tags
  script:
    - npm run package:linux
  artifacts:
    name: '$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG'
    paths:
      - release/*.AppImage
      - release/*.deb
      - release/*.rpm
      - release/*.pacman

package-mac:
  stage: package
  image: electronuserland/builder:latest
  only:
    - tags
  script:
    - npm run package:mac
  artifacts:
    name: '$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG'
    paths:
      - release/*.zip
