name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: 13
      - name: Install development dependencies
        run: npm run bootstrap
      - name: Check file styles and formattings
        run: npm run style:ci
      - name: Check types
        run: npm run ts:all
      - name: Build all packages
      - run: npm run build:all
      - name: Upload telestion-client-core build artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: telestion-client-core
          path: packages/telestion-client-core/build/
          retention-days: 7
      - name: Upload telestion-client-common build artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: telestion-client-common
          path: packages/telestion-client-common/build/
          retention-days: 7
