name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: actions/setup-node@v2.1.1
        with:
          node-version: 13
      - run: npm ci
      - run: npm run prettier:ci
      - run: npm run ts
      - run: npm run test
      - run: npm run build
