# Attribution goes to @pklaschka for this awesome action.
# Taken from the chat-xd-plugin workflows
# https://github.com/pklaschka/chat-xd-plugin/ (c) 2020 Pablo Klaschka (MIT-Licensed)

name: Lint

on: push

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2.3.4

      - name: Set up Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14

      # Eslint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm ci

      - name: Run linters
        uses: wearerequired/lint-action@v1.7.0
        with:
          github_token: ${{ secrets.github_token }}
          # Enable linters
          eslint: true
          eslint_extensions: 'js,jsx,ts,tsx'
          eslint_args: '--ignore-pattern node_modules/ --no-error-on-unmatched-pattern'
          prettier: true
          prettier_extensions: 'ts,tsx,js,jsx,json,html,css,scss,sass,yaml,yml,md'
