# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Lerna Release

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v2.3.4
      - name: Setup Node 💿
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14

      - name: Install lerna globally
        run: npm i -g lerna
      - name: Install development dependencies
        run: npm ci
      - name: Lerna version and GitHub release
        run: lerna version --conventional-commits --create-release github --yes
        env:
          GH_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}

      - name: Setup npm
        run: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish to npm registry
        run: lerna publish from-git --yes
