name: Test and Coverage

on: [push, pull_request]

jobs:
  jest-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v2.3.4
      - name: Setup Node 💿
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: Install development dependencies 📚
        run: npm ci

      - name: Run unit tests and generate coverage 🛃
        run: npm run test:unit

      - name: Publish code coverage to code climate 📠
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_REPORTER_ID }}
